import { useRef, useState, type FormEvent } from 'react';
import { PageHero } from '../../app/components/PageHero';
import { SearchField } from '../../app/components/SearchField';
import { Panel, SectionHeader, Tabs, FilterControl } from '../../app/components/UI';
import { Artwork } from '../../app/components/Artwork';
import { useWorkspace } from '../../app/data/WorkspaceProvider';
import { learningCategories, learningPaths, trendingSkills } from '../../app/data/catalog';
import { useConnect } from '../connect/ConnectProvider';
import { matchesPerson } from '../connect/selectors';
import { PersonRow } from '../connect/components/PersonRow';
import { ConnectionAction } from '../connect/components/ConnectionAction';
import { ProfilePreview } from '../profile/ProfilePreview';
import { useModalDialog } from '../../hooks/useModalDialog';
import type { LearningPath } from '../../app/data/models';
import type { Person } from '../connect/types';
export function LearnModule(){const workspace=useWorkspace();const{people}=useConnect();const[query,setQuery]=useState('');const[category,setCategory]=useState('All');const[learningTab,setLearningTab]=useState('In Progress');const[person,setPerson]=useState<Person|null>(null);const[path,setPath]=useState<LearningPath|null>(null);const[showAll,setShowAll]=useState(false);const[goalMessage,setGoalMessage]=useState('');const dialog=useRef<HTMLDialogElement>(null);useModalDialog(dialog,!!path);
  const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  const matching=learningPaths.filter(path=>(category==='All'||path.category===category||path.topics.some(topic=>topic.toLowerCase()===category.toLowerCase()))&&terms.every(term=>[path.title,path.description,path.category,...path.topics].join(' ').toLowerCase().includes(term)));
  const mentorIds=new Set(matching.flatMap(path=>path.mentorIds));const mentors=people.filter(person=>query||category!=='All'?mentorIds.has(person.id)||matchesPerson(person,query||category):showAll||['arjun','ishita','rohan','kavya'].includes(person.id));
  const tracked=workspace.learning.filter(record=>record.status===learningTab);const records=tracked.flatMap(record=>{const found=learningPaths.find(path=>path.id===record.pathId);return found?[{record,path:found}]:[];});
  function goal(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const value=String(new FormData(form).get('goal'));workspace.setGoal(value);form.reset();setGoalMessage('Learning goal saved.');}
  return <div className="module-columns learn-layout"><div className="module-main"><PageHero core="learn" title={<>Learn from people.<br/>Grow with a community.</>} description="Find the right mentors, resources and collaborators to learn new skills."><div className="search-with-filter"><SearchField label="Learning search" placeholder="What do you want to learn?" value={query} onChange={setQuery}/><FilterControl value={category} onChange={setCategory} options={learningCategories}/></div></PageHero>
    <div className="learning-chips chip-buttons">{['All',...learningCategories].map(item=><button key={item} aria-pressed={category===item} onClick={()=>setCategory(item)}>{item}</button>)}</div><SectionHeader title="Popular Learning Paths" action={showAll?'Show less':'View all'} onAction={()=>setShowAll(value=>!value)}/><div className="learning-path-grid">{matching.slice(0,showAll?matching.length:5).map(path=><button className="learning-path-card" key={path.id} onClick={()=>setPath(path)}><Artwork art={path.art}/><span><strong>{path.title}</strong><span>{path.description}</span><small>{path.mentorIds.length} {path.mentorIds.length===1?'mentor':'mentors'} &middot; {path.resources} resources</small></span></button>)}</div>{!matching.length&&<p className="workspace-empty">No paths found. Try a broader topic or another category.</p>}
    <SectionHeader title="Find Mentors" action={query||category!=='All'?'Clear filters':'View all'} onAction={()=>{setQuery('');setCategory('All');setShowAll(true);}}/><ul className="people-list mentor-grid">{mentors.slice(0,showAll?mentors.length:4).map(person=><PersonRow key={person.id} person={person} onPreview={setPerson} variant="mentor" action={<ConnectionAction person={person}/>}/>)}</ul>{!mentors.length&&<p className="workspace-empty">No matching mentors yet. Try another skill.</p>}
  </div><aside className="module-aside"><Panel title="My Learning"><Tabs label="My learning status" values={['In Progress','Saved','Completed']} value={learningTab} onChange={setLearningTab}/><div className="my-learning-list">{records.map(({path,record})=><button key={path.id} onClick={()=>setPath(path)}><Artwork art={path.art}/><span><strong>{path.title}</strong><progress max="100" value={record.progress} aria-label={path.title+' progress'}/><small>{record.progress}% &middot; {record.status}</small></span></button>)}{!records.length&&<div className="learning-empty"><p>{learningTab==='In Progress'?'Choose a path and start learning.':learningTab==='Saved'?'Save a path to return to it later.':'Your completed paths will appear here.'}</p>{learningTab==='In Progress'&&learningPaths.slice(0,3).map(path=><button key={path.id} onClick={()=>setPath(path)}><Artwork art={path.art}/><span>{path.title}<small>Explore path &rarr;</small></span></button>)}</div>}</div></Panel>
    <Panel title="Set a Learning Goal" description="Stay consistent. Build your future."><form className="stack-form" onSubmit={goal}><input name="goal" aria-label="Learning goal" placeholder="What do you want to learn?" required minLength={3} maxLength={160}/><button className="primary-button">Set Goal</button></form><p role="status" className="inline-status">{goalMessage}</p>{workspace.goals.slice(0,3).map(goal=><p key={goal} className="learning-goal">{goal}</p>)}</Panel>
    <Panel title="Trending Skills"><ol className="trending-list">{trendingSkills.map(skill=><li key={skill}><button onClick={()=>{setCategory('All');setQuery(skill);}}>{skill}<span>&#8599;</span></button></li>)}</ol></Panel><blockquote className="workspace-panel">&ldquo;A skill learned is a door opened to a brighter tomorrow.&rdquo;</blockquote></aside>
    <ProfilePreview person={person} onClose={()=>setPerson(null)} action={person?<ConnectionAction person={person} onRespond={()=>setPerson(null)}/>:undefined}/>
    <dialog className="workspace-dialog path-preview" ref={dialog} aria-labelledby="path-preview-title" onCancel={event=>{event.preventDefault();setPath(null);}} onClose={()=>setPath(null)} onClick={event=>{if(event.target===dialog.current)setPath(null);}}><div className="workspace-dialog-content"><button type="button" className="workspace-dialog-close quiet-button" onClick={()=>setPath(null)} autoFocus>Close</button>{path&&<><Artwork art={path.art}/><h2 id="path-preview-title">{path.title}</h2><p>{path.description}. Choose this as your learning focus and connect with people who can help.</p><p>{path.resources} example resources &middot; {path.mentorIds.length} mentors</p><div className="form-actions"><button className="secondary-button" onClick={()=>workspace.setLearning(path.id,'Saved')}>{workspace.learning.find(item=>item.pathId===path.id)?.status==='Saved'?'Saved':'Save path'}</button><button className="primary-button" onClick={()=>{workspace.setLearning(path.id,'In Progress');setLearningTab('In Progress');setPath(null);}}>Start Learning</button></div>{workspace.learning.some(item=>item.pathId===path.id)&&<button className="quiet-button" onClick={()=>{workspace.setLearning(path.id,'Completed');setLearningTab('Completed');setPath(null);}}>Mark completed</button>}</>}</div></dialog>
  </div>;
}
