import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useModalDialog } from '../../hooks/useModalDialog';
import { useWorkspace } from '../../app/data/WorkspaceProvider';
import { projectTypes } from '../../app/data/catalog';
export function ProjectComposer({initial,onClose}:{initial:{type:string;description:string}|null;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null); useModalDialog(dialog,!!initial); const {addProject}=useWorkspace(); const [files,setFiles]=useState<{name:string;size:number}[]>([]);
  useEffect(()=>{setFiles([]);},[initial]);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget,(event.nativeEvent as SubmitEvent).submitter);addProject({title:String(data.get('title')).trim(),description:String(data.get('description')).trim(),vision:String(data.get('vision')).trim(),type:String(data.get('type')),requiredSkills:String(data.get('skills')).split(',').map(item=>item.trim()).filter(Boolean),tags:[String(data.get('type'))],status:data.get('intent')==='draft'?'Draft':'Ongoing',art:'product',files});setFiles([]);onClose();}
  return <dialog ref={dialog} className="workspace-dialog project-composer" aria-labelledby="composer-title" onCancel={event=>{event.preventDefault();onClose();}} onClose={onClose} onClick={event=>{if(event.target===dialog.current)onClose();}}><div className="workspace-dialog-content"><button type="button" className="workspace-dialog-close quiet-button" onClick={onClose}>Close</button><h2 id="composer-title">Create a Project</h2><p>Turn your ideas into impact.</p>
    {initial&&<form key={initial.type+initial.description} onSubmit={submit} className="stack-form"><label>Project title<input autoFocus name="title" placeholder="Give your project a clear name..." required minLength={3} maxLength={100}/></label><label>Description<textarea name="description" defaultValue={initial.description} placeholder="Tell us about your project..." required minLength={10} maxLength={1000}/></label><label>Vision<textarea name="vision" placeholder="What do you want to achieve?" required maxLength={1000}/></label><label>Project type<select name="type" defaultValue={initial.type} required><option value="">Select a type</option>{projectTypes.map(type=><option key={type}>{type}</option>)}</select></label><label>Required skills or roles<input name="skills" placeholder="Design, research, photography..." maxLength={200}/></label><label className="file-drop" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();setFiles(Array.from(event.dataTransfer.files).map(file=>({name:file.name,size:file.size})));}}>Drop files here or browse<input type="file" multiple aria-label="Project files" onChange={event=>setFiles(Array.from(event.target.files??[]).map(file=>({name:file.name,size:file.size})))}/><span>{files.length?files.map(file=>file.name).join(', '):'Images, documents and other project material'}</span></label><div className="form-actions"><button className="secondary-button" name="intent" value="draft">Save Draft</button><button className="primary-button" name="intent" value="publish">Create Project</button></div></form>}
  </div></dialog>;
}
